blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/ruben-arushanyan/base-class/discussions
    about: For questions and answers, see the Discussions section.